[2022-02-25 23:19:57,667] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /users/register/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view users.views.RegisterView didn't return an HttpResponse object. It returned None instead.
[2022-02-25 23:19:57,671] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /users/register/ HTTP/1.1" 500 67713
[2022-02-25 23:25:19,736] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /users/register/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view users.views.RegisterView didn't return an HttpResponse object. It returned None instead.
[2022-02-25 23:25:19,739] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /users/register/ HTTP/1.1" 500 68009
[2022-02-25 23:38:46,245] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /users/register/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view users.views.RegisterView didn't return an HttpResponse object. It returned None instead.
[2022-02-25 23:38:46,251] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /users/register/ HTTP/1.1" 500 67878
[2022-02-25 23:38:55,835] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /users/register/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view users.views.RegisterView didn't return an HttpResponse object. It returned None instead.
[2022-02-25 23:38:55,838] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /users/register/ HTTP/1.1" 500 67877
[2022-02-25 23:44:31,193] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /users/register/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view users.views.RegisterView didn't return an HttpResponse object. It returned None instead.
[2022-02-25 23:44:31,199] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /users/register/ HTTP/1.1" 500 67878
[2022-02-25 23:44:46,040] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /users/register/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view users.views.RegisterView didn't return an HttpResponse object. It returned None instead.
[2022-02-25 23:44:46,043] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /users/register/ HTTP/1.1" 500 67877
[2022-02-25 23:44:50,195] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /users/register/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view users.views.RegisterView didn't return an HttpResponse object. It returned None instead.
[2022-02-25 23:44:50,200] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /users/register/ HTTP/1.1" 500 67877
[2022-02-25 23:44:51,102] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /users/register/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view users.views.RegisterView didn't return an HttpResponse object. It returned None instead.
[2022-02-25 23:44:51,106] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /users/register/ HTTP/1.1" 500 67877
[2022-02-25 23:58:55,140] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /users/register/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 188, in _get_response
    self.check_response(response, callback)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 311, in check_response
    "instead." % name
ValueError: The view users.views.RegisterView didn't return an HttpResponse object. It returned None instead.
[2022-02-25 23:58:55,143] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /users/register/ HTTP/1.1" 500 67284
[2022-02-26 22:28:51,914] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /users/register/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\template\defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
KeyError: 'templates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python37\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Django_aijia\my_aijia\my_aijia/apps\users\views.py", line 11, in get
    return render(request, 'register.html')
  File "D:\Python37\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Python37\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python37\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Python37\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Python37\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Python37\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Python37\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python37\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python37\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python37\lib\site-packages\django\template\defaulttags.py", line 1091, in load
    lib = find_library(parser, name)
  File "D:\Python37\lib\site-packages\django\template\defaulttags.py", line 1038, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'templates' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
[2022-02-26 22:28:51,946] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /users/register/ HTTP/1.1" 500 156449
[2022-02-26 22:28:53,636] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /users/register/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\template\defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
KeyError: 'templates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python37\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Django_aijia\my_aijia\my_aijia/apps\users\views.py", line 11, in get
    return render(request, 'register.html')
  File "D:\Python37\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Python37\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python37\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Python37\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Python37\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Python37\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Python37\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python37\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python37\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python37\lib\site-packages\django\template\defaulttags.py", line 1091, in load
    lib = find_library(parser, name)
  File "D:\Python37\lib\site-packages\django\template\defaulttags.py", line 1038, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'templates' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
[2022-02-26 22:28:53,654] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /users/register/ HTTP/1.1" 500 156449
[2022-02-26 22:28:54,824] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /users/register/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\template\defaulttags.py", line 1034, in find_library
    return parser.libraries[name]
KeyError: 'templates'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python37\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Django_aijia\my_aijia\my_aijia/apps\users\views.py", line 11, in get
    return render(request, 'register.html')
  File "D:\Python37\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Python37\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python37\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Python37\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Python37\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Python37\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Python37\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python37\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python37\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python37\lib\site-packages\django\template\defaulttags.py", line 1091, in load
    lib = find_library(parser, name)
  File "D:\Python37\lib\site-packages\django\template\defaulttags.py", line 1038, in find_library
    name, "\n".join(sorted(parser.libraries)),
django.template.exceptions.TemplateSyntaxError: 'templates' is not a registered tag library. Must be one of:
admin_list
admin_modify
admin_urls
cache
i18n
l10n
log
static
tz
[2022-02-26 22:28:54,842] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /users/register/ HTTP/1.1" 500 156449
