[2022-03-02 20:27:43,557] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /users/register/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python37\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Django_aijia\my_aijia\my_aijia/apps\users\views.py", line 39, in post
    login(request, user)
  File "D:\Python37\lib\site-packages\django\contrib\auth\__init__.py", line 111, in login
    request.session.cycle_key()
  File "D:\Python37\lib\site-packages\django\contrib\sessions\backends\base.py", line 344, in cycle_key
    self.create()
  File "D:\Python37\lib\site-packages\django\contrib\sessions\backends\cache.py", line 43, in create
    self._session_key = self._get_new_session_key()
  File "D:\Python37\lib\site-packages\django\contrib\sessions\backends\base.py", line 196, in _get_new_session_key
    if not self.exists(session_key):
  File "D:\Python37\lib\site-packages\django\contrib\sessions\backends\cache.py", line 70, in exists
    return bool(session_key) and (self.cache_key_prefix + session_key) in self._cache
  File "D:\Python37\lib\site-packages\django\core\cache\backends\base.py", line 212, in __contains__
    return self.has_key(key)
  File "D:\Python37\lib\site-packages\django_redis\cache.py", line 25, in _decorator
    return method(self, *args, **kwargs)
  File "D:\Python37\lib\site-packages\django_redis\cache.py", line 113, in has_key
    return self.client.has_key(*args, **kwargs)
  File "D:\Python37\lib\site-packages\django_redis\client\default.py", line 411, in has_key
    return client.exists(key)
  File "D:\Python37\lib\site-packages\redis\commands\core.py", line 1201, in exists
    return self.execute_command("EXISTS", *names)
  File "D:\Python37\lib\site-packages\redis\client.py", line 1180, in execute_command
    lambda error: self._disconnect_raise(conn, error),
  File "D:\Python37\lib\site-packages\redis\retry.py", line 45, in call_with_retry
    return do()
  File "D:\Python37\lib\site-packages\redis\client.py", line 1178, in <lambda>
    conn, command_name, *args, **options
  File "D:\Python37\lib\site-packages\redis\client.py", line 1152, in _send_command_parse_response
    conn.send_command(*args)
  File "D:\Python37\lib\site-packages\redis\connection.py", line 796, in send_command
    self.pack_command(*args), check_health=kwargs.get("check_health", True)
  File "D:\Python37\lib\site-packages\redis\connection.py", line 848, in pack_command
    for arg in map(self.encoder.encode, args):
  File "D:\Python37\lib\site-packages\redis\connection.py", line 111, in encode
    f"Invalid input of type: '{typename}'. "
redis.exceptions.DataError: Invalid input of type: 'CacheKey'. Convert to a bytes, string, int or float first.
[2022-03-02 20:27:43,574] [basehttp.py:161] [basehttp:log_message] [ERROR]- "POST /users/register/ HTTP/1.1" 500 152444
[2022-03-02 20:56:24,029] [log.py:230] [log:log_response] [ERROR]- Internal Server Error: /users/register/
Traceback (most recent call last):
  File "D:\Python37\lib\site-packages\django\core\handlers\exception.py", line 47, in inner
    response = get_response(request)
  File "D:\Python37\lib\site-packages\django\core\handlers\base.py", line 181, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "D:\Python37\lib\site-packages\django\views\generic\base.py", line 70, in view
    return self.dispatch(request, *args, **kwargs)
  File "D:\Python37\lib\site-packages\django\views\generic\base.py", line 98, in dispatch
    return handler(request, *args, **kwargs)
  File "D:\Django_aijia\my_aijia\my_aijia/apps\users\views.py", line 15, in get
    return render(request, 'register.html')
  File "D:\Python37\lib\site-packages\django\shortcuts.py", line 19, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "D:\Python37\lib\site-packages\django\template\loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "D:\Python37\lib\site-packages\django\template\loader.py", line 15, in get_template
    return engine.get_template(template_name)
  File "D:\Python37\lib\site-packages\django\template\backends\django.py", line 34, in get_template
    return Template(self.engine.get_template(template_name), self)
  File "D:\Python37\lib\site-packages\django\template\engine.py", line 143, in get_template
    template, origin = self.find_template(template_name)
  File "D:\Python37\lib\site-packages\django\template\engine.py", line 125, in find_template
    template = loader.get_template(name, skip=skip)
  File "D:\Python37\lib\site-packages\django\template\loaders\base.py", line 30, in get_template
    contents, origin, origin.template_name, self.engine,
  File "D:\Python37\lib\site-packages\django\template\base.py", line 155, in __init__
    self.nodelist = self.compile_nodelist()
  File "D:\Python37\lib\site-packages\django\template\base.py", line 193, in compile_nodelist
    return parser.parse()
  File "D:\Python37\lib\site-packages\django\template\base.py", line 478, in parse
    raise self.error(token, e)
  File "D:\Python37\lib\site-packages\django\template\base.py", line 476, in parse
    compiled_result = compile_func(self, token)
  File "D:\Python37\lib\site-packages\django\template\defaulttags.py", line 964, in do_if
    condition = TemplateIfParser(parser, bits).parse()
  File "D:\Python37\lib\site-packages\django\template\smartif.py", line 190, in parse
    retval = self.expression()
  File "D:\Python37\lib\site-packages\django\template\smartif.py", line 200, in expression
    left = t.nud(self)
  File "D:\Python37\lib\site-packages\django\template\smartif.py", line 77, in nud
    self.first = parser.expression(bp)
  File "D:\Python37\lib\site-packages\django\template\smartif.py", line 200, in expression
    left = t.nud(self)
  File "D:\Python37\lib\site-packages\django\template\smartif.py", line 23, in nud
    "Not expecting '%s' in this position in if tag." % self.id
django.template.exceptions.TemplateSyntaxError: Not expecting 'is' in this position in if tag.
[2022-03-02 20:56:24,043] [basehttp.py:161] [basehttp:log_message] [ERROR]- "GET /users/register/ HTTP/1.1" 500 173345
